import Foundation
import Combine

@MainActor
final class MeetSessionController: ObservableObject {
    static let shared = MeetSessionController()
    private let autoGeneratedIDLength = 8

    @Published var meetingIdInput = ""
    @Published var currentSession: MeetingSession?
    @Published var phase: MeetSessionPhase = .idle
    @Published var isBusy = false
    @Published var errorMessage: String?

    @Published var isMicrophoneMuted = false
    @Published var isCameraEnabled = true
    @Published var isScreenSharing = false

    @Published var participants: [MeetingParticipant] = []
    @Published var chatThreads: [MeetingChatThread] = [MeetingChatThread(id: "general", title: "General")]
    @Published var messages: [MeetingMessage] = []

    @Published var lobbyState = MeetingLobbyState()
    @Published var settings = MeetingSettingsState()
    @Published var summary = MeetingSummaryState()
    @Published private(set) var debugSnapshot: DailyDebugSnapshot = .empty

    private let resolver: MeetingResolver
    private let permissionService = MeetPermissionService()
    private var internalMeetingURL: URL?
    private var hasReportedWebJoin = false

    init(resolver: MeetingResolver = .shared) {
        self.resolver = resolver
    }

    var isMeetingIDFormatValid: Bool {
        isMeetingIDValid(meetingIdInput)
    }

    func validateMeetingID(_ value: String? = nil) -> Bool {
        let isValid = isMeetingIDValid(value ?? meetingIdInput)
        if !isValid {
            errorMessage = "Meeting ID must be 4-24 letters or numbers."
        } else if errorMessage == "Meeting ID must be 4-24 letters or numbers." {
            errorMessage = nil
        }
        return isValid
    }

    func generateMeetingID() -> String {
        let alphabet = Array("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")
        let fallback = Character("A")
        let id = String((0..<autoGeneratedIDLength).map { _ in alphabet.randomElement() ?? fallback })
        meetingIdInput = id
        return id
    }

    func createMeeting() async {
        let proposedID = meetingIdInput.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            ? generateMeetingID()
            : meetingIdInput

        guard validateMeetingID(proposedID) else { return }

        isBusy = true
        errorMessage = nil
        defer { isBusy = false }

        do {
            let session = try await resolver.createSession(with: proposedID)
            await transitionToLobby(session)
            DebugLogger.shared.log("Room creation completed for \(session.meetingId).", category: "MeetSession")
        } catch {
            phase = .failed
            errorMessage = error.localizedDescription
            DebugLogger.shared.log("Room creation failed: \(error.localizedDescription)", level: .error, category: "MeetSession")
        }
    }

    func joinMeeting() async {
        guard validateMeetingID() else { return }

        isBusy = true
        errorMessage = nil
        defer { isBusy = false }

        do {
            let session = try await resolver.joinSession(with: meetingIdInput)
            await transitionToLobby(session)
        } catch {
            phase = .failed
            errorMessage = error.localizedDescription
            DebugLogger.shared.log("Join failed: \(error.localizedDescription)", level: .error, category: "MeetSession")
        }
    }

    func runLobbyChecks() async {
        lobbyState.isLoadingParticipants = true
        lobbyState.isCheckingDevices = true

        async let mic = permissionService.checkMicrophonePermission()
        async let cam = permissionService.checkCameraPermission()

        lobbyState.microphonePermission = await mic
        lobbyState.cameraPermission = await cam
        lobbyState.isCheckingDevices = false
        lobbyState.isLoadingParticipants = false
    }

    func startMeeting() async {
        guard let currentSession else { return }
        guard internalMeetingURL != nil else {
            phase = .failed
            errorMessage = "Meeting URL is not available."
            return
        }
        await resolver.beginSession(currentSession)
        phase = .inMeeting
        hasReportedWebJoin = false
        addSystemMessage("Joining meeting…")
        DebugLogger.shared.log("WebRTC state changed: joining-meeting", category: "MeetSession")
        await refreshDebugSnapshot()
    }

    func leaveMeeting() async {
        guard let currentSession else { return }
        await resolver.endSession(currentSession)
        phase = .ended
        addSystemMessage("Meeting ended.")
        DebugLogger.shared.log("WebRTC state changed: disconnected", category: "MeetSession")
        hasReportedWebJoin = false
        participants = []
        await refreshDebugSnapshot()
    }

    func toggleMute() {
        isMicrophoneMuted.toggle()
        if let index = participants.firstIndex(where: { $0.id == "local" }) {
            participants[index].isMuted = isMicrophoneMuted
        }
        DebugLogger.shared.log(isMicrophoneMuted ? "Microphone muted." : "Microphone unmuted.", category: "MeetSession")
    }

    func toggleCamera() {
        isCameraEnabled.toggle()
        if let index = participants.firstIndex(where: { $0.id == "local" }) {
            participants[index].hasVideo = isCameraEnabled
        }
        DebugLogger.shared.log(isCameraEnabled ? "Camera enabled." : "Camera disabled.", category: "MeetSession")
    }

    func toggleScreenShare() {
        isScreenSharing.toggle()
        DebugLogger.shared.log(isScreenSharing ? "Screen share started." : "Screen share stopped.", category: "MeetSession")
    }

    func sendMessage(_ text: String, threadId: String = "general") {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        messages.append(
            MeetingMessage(
                id: UUID().uuidString,
                threadId: threadId,
                senderName: "You",
                text: trimmed,
                sentAt: Date(),
                isSystem: false
            )
        )
    }

    func addThread(named title: String) {
        let trimmed = title.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        chatThreads.append(MeetingChatThread(id: UUID().uuidString, title: trimmed))
    }

    func updateDeveloperAPIKey(_ value: String) async {
        await resolver.updateDeveloperAPIKey(value)
        await refreshDebugSnapshot()
    }

    func refreshDebugSnapshot() async {
        debugSnapshot = await resolver.fetchDebugSnapshot()
    }

    func webViewDidStartJoining() {
        DebugLogger.shared.log("WebRTC state changed: joining-meeting", category: "MeetSession")
    }

    func webViewDidJoin() {
        guard !hasReportedWebJoin else { return }
        hasReportedWebJoin = true
        ensureLocalParticipant()
        addSystemMessage("Meeting connected.")
        DebugLogger.shared.log("WebRTC state changed: joined-meeting", category: "MeetSession")
    }

    func webViewDidLeaveUnexpectedly() {
        guard phase == .inMeeting else { return }
        if let currentSession {
            Task {
                await resolver.endSession(currentSession)
                await refreshDebugSnapshot()
            }
        }
        phase = .ended
        hasReportedWebJoin = false
        participants = []
        addSystemMessage("Meeting connection ended.")
        DebugLogger.shared.log("WebRTC state changed: left-meeting", category: "MeetSession")
    }

    func webViewDidFail(_ message: String) {
        if let currentSession {
            Task {
                await resolver.endSession(currentSession)
                await refreshDebugSnapshot()
            }
        }
        hasReportedWebJoin = false
        phase = .failed
        errorMessage = message
        DebugLogger.shared.log("Join failed: \(message)", level: .error, category: "MeetSession")
    }

    func webViewURL() -> URL? {
        internalMeetingURL
    }

    private func transitionToLobby(_ session: MeetingSession) async {
        currentSession = session
        meetingIdInput = session.meetingId
        internalMeetingURL = await resolver.internalRoomURL(for: session)
        phase = .lobby
        hasReportedWebJoin = false
        summary = MeetingSummaryState(
            recap: "AI recap will be generated after this meeting session.",
            actionItems: ["Capture blockers", "Summarize next steps"],
            transcriptPreview: "Transcript preview entry point is ready for integration."
        )
        participants = []
        messages = []
        await refreshDebugSnapshot()
        addSystemMessage("Session prepared for meeting ID \(session.meetingId).")
    }

    private func addSystemMessage(_ text: String) {
        messages.append(
            MeetingMessage(
                id: UUID().uuidString,
                threadId: "general",
                senderName: "System",
                text: text,
                sentAt: Date(),
                isSystem: true
            )
        )
    }

    private func isMeetingIDValid(_ value: String) -> Bool {
        let candidate = value
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .uppercased()
        let allowed = CharacterSet.alphanumerics
        return (4...24).contains(candidate.count) && candidate.unicodeScalars.allSatisfy { allowed.contains($0) }
    }

    private func ensureLocalParticipant() {
        if let index = participants.firstIndex(where: { $0.id == "local" }) {
            participants[index].isMuted = isMicrophoneMuted
            participants[index].hasVideo = isCameraEnabled
            return
        }
        participants.insert(
            MeetingParticipant(
                id: "local",
                displayName: "You",
                joinedAt: Date(),
                isSpeaking: false,
                isMuted: isMicrophoneMuted,
                hasVideo: isCameraEnabled
            ),
            at: 0
        )
    }
}
