/*
 * Summary: Service for resolving and managing meeting sessions.
 * Changes: Refactored to use unified logger and native DailyCallManager integration.
 */

import Foundation
import Daily

/// Actor for resolving meeting IDs and managing session state.
actor MeetingResolver {
    static let shared = MeetingResolver()

    private let dailyService: DailyService

    init(dailyService: DailyService = .shared) {
        self.dailyService = dailyService
    }

    /// Creates a new meeting session via the Daily API.
    func createSession(with meetingId: String?) async throws -> MeetingSession {
        let logMeetingID = meetingId ?? "(generated by Daily API)"
        MeetingLogger.info("Create session attempt for meeting ID \(logMeetingID).", category: MeetingLogger.shared)
        let session = try await dailyService.createRoom(for: meetingId)
        MeetingLogger.info("Create session success for \(session.meetingId).", category: MeetingLogger.shared)
        return session
    }

    /// Generates a new unique meeting ID.
    func generateMeetingID() async throws -> String {
        MeetingLogger.info("Generate meeting ID using Daily API.", category: MeetingLogger.shared)
        let generatedID = try await dailyService.generateMeetingID()
        MeetingLogger.info("Generated Daily meeting ID \(generatedID).", category: MeetingLogger.shared)
        return generatedID
    }

    /// Joins an existing meeting session.
    func joinSession(with meetingId: String) async throws -> MeetingSession {
        MeetingLogger.info("Join attempt for meeting ID \(meetingId).", category: MeetingLogger.shared)
        let session = try await dailyService.resolveMeetingID(meetingId)
        MeetingLogger.info("Join success for \(session.meetingId).", category: MeetingLogger.shared)
        return session
    }

    /// Signals the start of a session.
    func beginSession(_ session: MeetingSession) async {
        await dailyService.beginSession(session)
    }

    /// Signals the end of a session.
    func endSession(_ session: MeetingSession) async {
        await dailyService.endSession(session)
    }

    /// Returns the internal Daily room URL for a session.
    func internalRoomURL(for session: MeetingSession) async -> URL? {
        await dailyService.internalRoomURL(for: session)
    }

    /// Updates the developer API key.
    func updateDeveloperAPIKey(_ value: String) async {
        await dailyService.setDeveloperAPIKey(value)
    }

    /// Fetches a debug snapshot of current sessions.
    func fetchDebugSnapshot() async -> DailyDebugSnapshot {
        await dailyService.debugSnapshot()
    }
}
