import SwiftUI

struct AgentPromptOptimizerView: View {
    let originalPrompt: String
    @Binding var optimizedPrompt: String
    @Environment(\.dismiss) var dismiss

    @State private var result: String = ""
    @State private var isOptimizing = false
    @State private var error: String?

    var body: some View {
        NavigationView {
            VStack {
                if isOptimizing {
                    VStack(spacing: 20) {
                        ProgressView()
                            .scaleEffect(1.5)
                        Text("Optimizing your prompt...")
                            .foregroundColor(.secondary)
                    }
                    .frame(maxHeight: .infinity)
                } else if let error = error {
                    VStack(spacing: 16) {
                        Image(systemName: "exclamationmark.triangle.fill")
                            .font(.largeTitle)
                            .foregroundColor(.red)
                        Text(error)
                            .multilineTextAlignment(.center)
                            .padding()
                        Button("Retry") {
                            optimize()
                        }
                        .buttonStyle(.bordered)
                    }
                    .frame(maxHeight: .infinity)
                } else {
                    ScrollView {
                        VStack(alignment: .leading, spacing: 16) {
                            Text("Optimized Prompt")
                                .font(.headline)

                            TextEditor(text: $result)
                                .frame(minHeight: 300)
                                .padding(8)
                                .background(Color(.secondarySystemBackground))
                                .cornerRadius(8)

                            Text("This prompt was generated by AI to be more specific and actionable for the Jules agent.")
                                .font(.caption)
                                .foregroundColor(.secondary)
                        }
                        .padding()
                    }
                }

                if !isOptimizing && error == nil {
                    Button(action: apply) {
                        Text("Apply Optimized Prompt")
                            .font(.headline)
                            .frame(maxWidth: .infinity)
                            .padding()
                            .background(Color.blue)
                            .foregroundColor(.white)
                            .cornerRadius(12)
                    }
                    .padding()
                }
            }
            .navigationTitle("Prompt Optimizer")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
            }
            .task {
                optimize()
            }
        }
    }

    private func optimize() {
        isOptimizing = true
        error = nil

        let systemPrompt = """
        You are an expert prompt engineer for an AI coding agent named Jules.
        Your task is to take a user's potentially vague request and transform it into a highly specific, informational, and actionable agent prompt.
        The optimized prompt should:
        1. Explicitly state the goals.
        2. Mention technical details or patterns if relevant.
        3. Define scope clearly.
        4. Use a professional, directive tone.
        Return ONLY the optimized prompt text.
        """

        Task {
            do {
                let optimized = try await AIService.shared.processText(prompt: originalPrompt, systemPrompt: systemPrompt)
                await MainActor.run {
                    self.result = optimized
                    self.isOptimizing = false
                }
            } catch {
                await MainActor.run {
                    self.error = error.localizedDescription
                    self.isOptimizing = false
                }
            }
        }
    }

    private func apply() {
        optimizedPrompt = result
        dismiss()
    }
}
