import Foundation

struct TriviaQuestion: Identifiable {
    let id = UUID()
    let category: String
    let question: String
    let answers: [String]
    let correctIndex: Int
}

struct TriviaCrushQuestionBank {
    static let questions: [TriviaQuestion] = [
        // Science (35+)
        TriviaQuestion(category: "Science", question: "What is the chemical symbol for gold?", answers: ["Au", "Ag", "Fe", "Cu"], correctIndex: 0),
        TriviaQuestion(category: "Science", question: "How many bones are in the adult human body?", answers: ["186", "206", "226", "256"], correctIndex: 1),
        TriviaQuestion(category: "Science", question: "What planet is known as the Red Planet?", answers: ["Venus", "Jupiter", "Mars", "Saturn"], correctIndex: 2),
        TriviaQuestion(category: "Science", question: "What gas do plants absorb from the atmosphere?", answers: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"], correctIndex: 2),
        TriviaQuestion(category: "Science", question: "What is the speed of light in km/s approximately?", answers: ["150,000", "200,000", "300,000", "400,000"], correctIndex: 2),
        TriviaQuestion(category: "Science", question: "What is the hardest natural substance?", answers: ["Iron", "Quartz", "Topaz", "Diamond"], correctIndex: 3),
        TriviaQuestion(category: "Science", question: "What is the smallest unit of matter?", answers: ["Molecule", "Atom", "Electron", "Proton"], correctIndex: 1),
        TriviaQuestion(category: "Science", question: "Which planet has the most moons?", answers: ["Jupiter", "Saturn", "Uranus", "Neptune"], correctIndex: 1),
        TriviaQuestion(category: "Science", question: "What is the boiling point of water in Celsius?", answers: ["90", "95", "100", "110"], correctIndex: 2),
        TriviaQuestion(category: "Science", question: "DNA stands for:", answers: ["Deoxyribonucleic acid", "Dinitrogen acid", "Dynamic nuclear acid", "Double nucleic acid"], correctIndex: 0),
        TriviaQuestion(category: "Science", question: "What force keeps planets orbiting the sun?", answers: ["Magnetism", "Friction", "Gravity", "Inertia"], correctIndex: 2),
        TriviaQuestion(category: "Science", question: "What organ pumps blood in the human body?", answers: ["Lungs", "Brain", "Liver", "Heart"], correctIndex: 3),
        TriviaQuestion(category: "Science", question: "What element does O represent?", answers: ["Osmium", "Oxygen", "Oganesson", "Oxide"], correctIndex: 1),
        TriviaQuestion(category: "Science", question: "What is the closest star to Earth?", answers: ["Proxima Centauri", "Sirius", "The Sun", "Alpha Centauri"], correctIndex: 2),
        TriviaQuestion(category: "Science", question: "How many chromosomes do humans have?", answers: ["23", "44", "46", "48"], correctIndex: 2),
        TriviaQuestion(category: "Science", question: "What is the pH of pure water?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(category: "Science", question: "What is the largest organ in the human body?", answers: ["Liver", "Brain", "Skin", "Lungs"], correctIndex: 2),
        TriviaQuestion(category: "Science", question: "What type of animal is a dolphin?", answers: ["Fish", "Mammal", "Reptile", "Amphibian"], correctIndex: 1),
        TriviaQuestion(category: "Science", question: "What gas makes up most of Earth's atmosphere?", answers: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], correctIndex: 2),
        TriviaQuestion(category: "Science", question: "What part of the cell contains DNA?", answers: ["Cytoplasm", "Membrane", "Nucleus", "Ribosome"], correctIndex: 2),
        TriviaQuestion(category: "Science", question: "What is the main gas found in the Sun?", answers: ["Oxygen", "Helium", "Carbon", "Hydrogen"], correctIndex: 3),
        TriviaQuestion(category: "Science", question: "Sound travels fastest through:", answers: ["Air", "Water", "Vacuum", "Steel"], correctIndex: 3),
        TriviaQuestion(category: "Science", question: "What vitamin does sunlight provide?", answers: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], correctIndex: 3),
        TriviaQuestion(category: "Science", question: "What is the chemical formula for table salt?", answers: ["NaCl", "KCl", "CaCl2", "NaOH"], correctIndex: 0),
        TriviaQuestion(category: "Science", question: "How many planets are in our solar system?", answers: ["7", "8", "9", "10"], correctIndex: 1),
        TriviaQuestion(category: "Science", question: "What is the powerhouse of the cell?", answers: ["Nucleus", "Ribosome", "Mitochondria", "Golgi body"], correctIndex: 2),
        TriviaQuestion(category: "Science", question: "What is the freezing point of water in Fahrenheit?", answers: ["0", "32", "100", "212"], correctIndex: 1),
        TriviaQuestion(category: "Science", question: "What blood type is the universal donor?", answers: ["A", "B", "AB", "O negative"], correctIndex: 3),
        TriviaQuestion(category: "Science", question: "What is the most abundant element in the universe?", answers: ["Oxygen", "Carbon", "Helium", "Hydrogen"], correctIndex: 3),
        TriviaQuestion(category: "Science", question: "How many teeth does an adult human have?", answers: ["28", "30", "32", "34"], correctIndex: 2),
        TriviaQuestion(category: "Science", question: "Which planet is the largest?", answers: ["Saturn", "Jupiter", "Neptune", "Uranus"], correctIndex: 1),
        TriviaQuestion(category: "Science", question: "What is the chemical symbol for iron?", answers: ["Ir", "In", "Fe", "Fr"], correctIndex: 2),
        TriviaQuestion(category: "Science", question: "What is the study of fossils called?", answers: ["Archaeology", "Paleontology", "Geology", "Biology"], correctIndex: 1),
        TriviaQuestion(category: "Science", question: "What is the atomic number of carbon?", answers: ["4", "6", "8", "12"], correctIndex: 1),
        TriviaQuestion(category: "Science", question: "What type of rock is formed from cooled lava?", answers: ["Sedimentary", "Metamorphic", "Igneous", "Limestone"], correctIndex: 2),

        // History (35+)
        TriviaQuestion(category: "History", question: "In what year did World War II end?", answers: ["1943", "1944", "1945", "1946"], correctIndex: 2),
        TriviaQuestion(category: "History", question: "Who was the first President of the United States?", answers: ["Thomas Jefferson", "George Washington", "Abraham Lincoln", "John Adams"], correctIndex: 1),
        TriviaQuestion(category: "History", question: "The Great Wall of China was primarily built to protect against:", answers: ["Mongol invasions", "Japanese attacks", "Russian expansion", "Indian trade routes"], correctIndex: 0),
        TriviaQuestion(category: "History", question: "Who discovered America in 1492?", answers: ["Vasco da Gama", "Ferdinand Magellan", "Christopher Columbus", "Amerigo Vespucci"], correctIndex: 2),
        TriviaQuestion(category: "History", question: "The French Revolution began in:", answers: ["1776", "1789", "1799", "1804"], correctIndex: 1),
        TriviaQuestion(category: "History", question: "Who was known as the Iron Lady?", answers: ["Queen Victoria", "Margaret Thatcher", "Indira Gandhi", "Angela Merkel"], correctIndex: 1),
        TriviaQuestion(category: "History", question: "What ancient civilization built the pyramids?", answers: ["Romans", "Greeks", "Egyptians", "Persians"], correctIndex: 2),
        TriviaQuestion(category: "History", question: "In what year did the Titanic sink?", answers: ["1910", "1912", "1914", "1916"], correctIndex: 1),
        TriviaQuestion(category: "History", question: "Who wrote the Declaration of Independence?", answers: ["Benjamin Franklin", "John Adams", "Thomas Jefferson", "James Madison"], correctIndex: 2),
        TriviaQuestion(category: "History", question: "The Cold War was between:", answers: ["USA and China", "USA and USSR", "UK and Germany", "France and Russia"], correctIndex: 1),
        TriviaQuestion(category: "History", question: "Who was the first man to walk on the moon?", answers: ["Buzz Aldrin", "Neil Armstrong", "John Glenn", "Yuri Gagarin"], correctIndex: 1),
        TriviaQuestion(category: "History", question: "What year did the Berlin Wall fall?", answers: ["1987", "1988", "1989", "1990"], correctIndex: 2),
        TriviaQuestion(category: "History", question: "Who painted the Mona Lisa?", answers: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello"], correctIndex: 2),
        TriviaQuestion(category: "History", question: "What empire was ruled by Genghis Khan?", answers: ["Ottoman", "Roman", "Mongol", "Persian"], correctIndex: 2),
        TriviaQuestion(category: "History", question: "Which country gifted the Statue of Liberty to the US?", answers: ["England", "Spain", "Italy", "France"], correctIndex: 3),
        TriviaQuestion(category: "History", question: "The Renaissance began in which country?", answers: ["France", "England", "Italy", "Spain"], correctIndex: 2),
        TriviaQuestion(category: "History", question: "Who was the first Emperor of Rome?", answers: ["Julius Caesar", "Augustus", "Nero", "Caligula"], correctIndex: 1),
        TriviaQuestion(category: "History", question: "What year was the Magna Carta signed?", answers: ["1066", "1215", "1348", "1492"], correctIndex: 1),
        TriviaQuestion(category: "History", question: "Which war was fought between the North and South in the US?", answers: ["Revolutionary War", "War of 1812", "Civil War", "World War I"], correctIndex: 2),
        TriviaQuestion(category: "History", question: "What ancient city was buried by Mt. Vesuvius?", answers: ["Athens", "Rome", "Pompeii", "Carthage"], correctIndex: 2),
        TriviaQuestion(category: "History", question: "Who was the first woman to fly solo across the Atlantic?", answers: ["Bessie Coleman", "Amelia Earhart", "Harriet Quimby", "Jacqueline Cochran"], correctIndex: 1),
        TriviaQuestion(category: "History", question: "The Industrial Revolution began in:", answers: ["France", "Germany", "United States", "England"], correctIndex: 3),
        TriviaQuestion(category: "History", question: "Who invented the printing press?", answers: ["Thomas Edison", "Johannes Gutenberg", "Benjamin Franklin", "Nikola Tesla"], correctIndex: 1),
        TriviaQuestion(category: "History", question: "What was the last dynasty of China?", answers: ["Ming", "Song", "Qing", "Tang"], correctIndex: 2),
        TriviaQuestion(category: "History", question: "The Hundred Years War was between:", answers: ["England and France", "Spain and Portugal", "Rome and Greece", "Germany and Poland"], correctIndex: 0),
        TriviaQuestion(category: "History", question: "Who was the leader of Nazi Germany?", answers: ["Mussolini", "Stalin", "Hitler", "Franco"], correctIndex: 2),
        TriviaQuestion(category: "History", question: "What year was the United Nations founded?", answers: ["1940", "1945", "1950", "1955"], correctIndex: 1),
        TriviaQuestion(category: "History", question: "The Silk Road connected China to:", answers: ["Japan", "India", "Africa", "Europe"], correctIndex: 3),
        TriviaQuestion(category: "History", question: "Who was Cleopatra?", answers: ["Roman empress", "Greek goddess", "Egyptian pharaoh", "Persian queen"], correctIndex: 2),
        TriviaQuestion(category: "History", question: "The Vietnam War ended in what year?", answers: ["1973", "1975", "1977", "1979"], correctIndex: 1),
        TriviaQuestion(category: "History", question: "What civilization invented democracy?", answers: ["Roman", "Egyptian", "Greek", "Persian"], correctIndex: 2),
        TriviaQuestion(category: "History", question: "Who led India to independence?", answers: ["Jawaharlal Nehru", "Mahatma Gandhi", "Subhas Bose", "B.R. Ambedkar"], correctIndex: 1),
        TriviaQuestion(category: "History", question: "When was the first airplane flight?", answers: ["1895", "1899", "1903", "1910"], correctIndex: 2),
        TriviaQuestion(category: "History", question: "What was the name of the first satellite in space?", answers: ["Explorer 1", "Sputnik", "Vanguard", "Luna 1"], correctIndex: 1),
        TriviaQuestion(category: "History", question: "Who was the longest-reigning British monarch before Elizabeth II?", answers: ["Queen Victoria", "King George III", "King Henry VIII", "King Edward VII"], correctIndex: 0),

        // Sports (35+)
        TriviaQuestion(category: "Sports", question: "How many players are on a soccer team?", answers: ["9", "10", "11", "12"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "In tennis, what is a score of zero called?", answers: ["Nil", "Love", "Zero", "Nothing"], correctIndex: 1),
        TriviaQuestion(category: "Sports", question: "The Olympics are held every how many years?", answers: ["2", "3", "4", "5"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "What sport is played at Wimbledon?", answers: ["Cricket", "Golf", "Tennis", "Soccer"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "How many holes are in a standard round of golf?", answers: ["9", "12", "16", "18"], correctIndex: 3),
        TriviaQuestion(category: "Sports", question: "In basketball, how many points is a free throw worth?", answers: ["1", "2", "3", "4"], correctIndex: 0),
        TriviaQuestion(category: "Sports", question: "What country invented cricket?", answers: ["India", "Australia", "England", "South Africa"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "How many periods are in an ice hockey game?", answers: ["2", "3", "4", "5"], correctIndex: 1),
        TriviaQuestion(category: "Sports", question: "In which sport would you perform a slam dunk?", answers: ["Volleyball", "Tennis", "Basketball", "Soccer"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "What is the national sport of Japan?", answers: ["Karate", "Judo", "Sumo", "Kendo"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "How long is a marathon in miles approximately?", answers: ["20.2", "24.2", "26.2", "28.2"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "What sport uses a shuttlecock?", answers: ["Tennis", "Badminton", "Squash", "Table Tennis"], correctIndex: 1),
        TriviaQuestion(category: "Sports", question: "How many players are on a baseball team?", answers: ["7", "8", "9", "10"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "The World Cup is associated with which sport?", answers: ["Cricket", "Rugby", "Soccer", "Hockey"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "What is the highest score in a single frame of bowling?", answers: ["100", "200", "250", "300"], correctIndex: 3),
        TriviaQuestion(category: "Sports", question: "In what sport do you use a puck?", answers: ["Field Hockey", "Ice Hockey", "Lacrosse", "Polo"], correctIndex: 1),
        TriviaQuestion(category: "Sports", question: "How many rings are on the Olympic flag?", answers: ["3", "4", "5", "6"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "What is the diameter of a basketball hoop in inches?", answers: ["14", "16", "18", "20"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "In football, how many points is a touchdown worth?", answers: ["3", "5", "6", "7"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "What country won the first FIFA World Cup?", answers: ["Brazil", "Uruguay", "Argentina", "Italy"], correctIndex: 1),
        TriviaQuestion(category: "Sports", question: "Which Grand Slam is played on clay?", answers: ["Wimbledon", "US Open", "Australian Open", "French Open"], correctIndex: 3),
        TriviaQuestion(category: "Sports", question: "How many quarters are in an NBA game?", answers: ["2", "3", "4", "5"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "What is the highest belt in karate?", answers: ["Red", "Brown", "Black", "White"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "In swimming, what stroke is also called the front crawl?", answers: ["Butterfly", "Backstroke", "Breaststroke", "Freestyle"], correctIndex: 3),
        TriviaQuestion(category: "Sports", question: "What is the ball used in rugby called?", answers: ["Pigskin", "Match ball", "Gilbert", "Spheroid"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "Which country has won the most Olympic gold medals?", answers: ["China", "Russia", "United States", "Great Britain"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "What sport is Tiger Woods famous for?", answers: ["Tennis", "Golf", "Cricket", "Boxing"], correctIndex: 1),
        TriviaQuestion(category: "Sports", question: "How many sets does a man play in a Grand Slam tennis match?", answers: ["3", "4", "5", "6"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "In what year were the first modern Olympics held?", answers: ["1888", "1892", "1896", "1900"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "What is the term for three strikes in a row in bowling?", answers: ["Double", "Triple", "Turkey", "Hat trick"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "What sport does Serena Williams play?", answers: ["Golf", "Basketball", "Tennis", "Volleyball"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "How many dimples are on a typical golf ball?", answers: ["236", "336", "436", "536"], correctIndex: 1),
        TriviaQuestion(category: "Sports", question: "In which sport would you find a halfpipe?", answers: ["Skiing", "Snowboarding", "Skateboarding", "All of these"], correctIndex: 3),
        TriviaQuestion(category: "Sports", question: "What is the width of a soccer goal in feet?", answers: ["18", "20", "24", "28"], correctIndex: 2),
        TriviaQuestion(category: "Sports", question: "Which boxer was known as The Greatest?", answers: ["Mike Tyson", "Muhammad Ali", "Floyd Mayweather", "Joe Louis"], correctIndex: 1),

        // Pop Culture (35+)
        TriviaQuestion(category: "Pop Culture", question: "Who played Iron Man in the MCU?", answers: ["Chris Evans", "Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo"], correctIndex: 1),
        TriviaQuestion(category: "Pop Culture", question: "What is the highest-grossing film of all time?", answers: ["Endgame", "Avatar", "Titanic", "Star Wars"], correctIndex: 1),
        TriviaQuestion(category: "Pop Culture", question: "Which band performed Bohemian Rhapsody?", answers: ["The Beatles", "Led Zeppelin", "Queen", "Pink Floyd"], correctIndex: 2),
        TriviaQuestion(category: "Pop Culture", question: "What is the name of Harry Potter\'s owl?", answers: ["Errol", "Pigwidgeon", "Hedwig", "Scabbers"], correctIndex: 2),
        TriviaQuestion(category: "Pop Culture", question: "Who is the voice of Woody in Toy Story?", answers: ["Tim Allen", "Tom Hanks", "Billy Crystal", "Robin Williams"], correctIndex: 1),
        TriviaQuestion(category: "Pop Culture", question: "What year was the first iPhone released?", answers: ["2005", "2006", "2007", "2008"], correctIndex: 2),
        TriviaQuestion(category: "Pop Culture", question: "Who wrote the Game of Thrones book series?", answers: ["J.R.R. Tolkien", "George R.R. Martin", "Stephen King", "Brandon Sanderson"], correctIndex: 1),
        TriviaQuestion(category: "Pop Culture", question: "What streaming service produced Stranger Things?", answers: ["Hulu", "Amazon Prime", "Netflix", "Disney+"], correctIndex: 2),
        TriviaQuestion(category: "Pop Culture", question: "Who is known as the King of Pop?", answers: ["Elvis Presley", "Prince", "Michael Jackson", "Freddie Mercury"], correctIndex: 2),
        TriviaQuestion(category: "Pop Culture", question: "What is the name of the fictional country in Black Panther?", answers: ["Genovia", "Wakanda", "Zamunda", "Latveria"], correctIndex: 1),
        TriviaQuestion(category: "Pop Culture", question: "Who directed Jurassic Park?", answers: ["James Cameron", "Steven Spielberg", "George Lucas", "Ridley Scott"], correctIndex: 1),
        TriviaQuestion(category: "Pop Culture", question: "What social media platform uses a bird logo?", answers: ["Facebook", "Instagram", "Twitter", "TikTok"], correctIndex: 2),
        TriviaQuestion(category: "Pop Culture", question: "In Friends, what is the name of Ross\'s monkey?", answers: ["Marcel", "George", "Jack", "Clyde"], correctIndex: 0),
        TriviaQuestion(category: "Pop Culture", question: "What video game features a plumber named Mario?", answers: ["Sonic", "Zelda", "Super Mario Bros", "Donkey Kong"], correctIndex: 2),
        TriviaQuestion(category: "Pop Culture", question: "Who sang Shape of You?", answers: ["Justin Bieber", "Ed Sheeran", "Bruno Mars", "The Weeknd"], correctIndex: 1),
        TriviaQuestion(category: "Pop Culture", question: "What Disney princess has ice powers?", answers: ["Elsa", "Anna", "Rapunzel", "Moana"], correctIndex: 0),
        TriviaQuestion(category: "Pop Culture", question: "What is the name of Batman\'s butler?", answers: ["Jarvis", "Alfred", "Watson", "Jeeves"], correctIndex: 1),
        TriviaQuestion(category: "Pop Culture", question: "Which Marvel character wields Mjolnir?", answers: ["Captain America", "Iron Man", "Thor", "Hulk"], correctIndex: 2),
        TriviaQuestion(category: "Pop Culture", question: "What TV show features dragons and ice walkers?", answers: ["The Witcher", "Game of Thrones", "Lord of the Rings", "Vikings"], correctIndex: 1),
        TriviaQuestion(category: "Pop Culture", question: "Who played Jack in Titanic?", answers: ["Brad Pitt", "Tom Cruise", "Leonardo DiCaprio", "Johnny Depp"], correctIndex: 2),
        TriviaQuestion(category: "Pop Culture", question: "What game features building and mining blocks?", answers: ["Fortnite", "Minecraft", "Roblox", "Terraria"], correctIndex: 1),
        TriviaQuestion(category: "Pop Culture", question: "Who is the lead singer of Coldplay?", answers: ["Bono", "Chris Martin", "Thom Yorke", "Brandon Flowers"], correctIndex: 1),
        TriviaQuestion(category: "Pop Culture", question: "What anime features a character named Goku?", answers: ["Naruto", "One Piece", "Dragon Ball", "Bleach"], correctIndex: 2),
        TriviaQuestion(category: "Pop Culture", question: "Who created Facebook?", answers: ["Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Jeff Bezos"], correctIndex: 2),
        TriviaQuestion(category: "Pop Culture", question: "What is the name of the wizarding school in Harry Potter?", answers: ["Beauxbatons", "Durmstrang", "Hogwarts", "Ilvermorny"], correctIndex: 2),
        TriviaQuestion(category: "Pop Culture", question: "Who played the Joker in The Dark Knight?", answers: ["Jack Nicholson", "Joaquin Phoenix", "Jared Leto", "Heath Ledger"], correctIndex: 3),
        TriviaQuestion(category: "Pop Culture", question: "What is the currency in the game Fortnite?", answers: ["Coins", "V-Bucks", "Gems", "Credits"], correctIndex: 1),
        TriviaQuestion(category: "Pop Culture", question: "Who sang Thriller?", answers: ["Prince", "Michael Jackson", "Whitney Houston", "Madonna"], correctIndex: 1),
        TriviaQuestion(category: "Pop Culture", question: "What platform is known for short-form videos?", answers: ["YouTube", "LinkedIn", "TikTok", "Pinterest"], correctIndex: 2),
        TriviaQuestion(category: "Pop Culture", question: "What is Baby Yoda\'s real name?", answers: ["Yoda", "Grogu", "Yaddle", "Vandar"], correctIndex: 1),
        TriviaQuestion(category: "Pop Culture", question: "Who directed Inception?", answers: ["Christopher Nolan", "Martin Scorsese", "Quentin Tarantino", "David Fincher"], correctIndex: 0),
        TriviaQuestion(category: "Pop Culture", question: "What is the name of Beyoncé\'s alter ego?", answers: ["Queen B", "Sasha Fierce", "Lemonade", "Ivy Park"], correctIndex: 1),
        TriviaQuestion(category: "Pop Culture", question: "In The Office, what is Michael Scott\'s catchphrase?", answers: ["Bears, Beets, Battlestar", "That\'s what she said", "I declare bankruptcy", "Dwight you ignorant"], correctIndex: 1),
        TriviaQuestion(category: "Pop Culture", question: "What movie features a DeLorean time machine?", answers: ["The Terminator", "Back to the Future", "Bill and Ted", "Time Bandits"], correctIndex: 1),
        TriviaQuestion(category: "Pop Culture", question: "Who is the creator of SpongeBob SquarePants?", answers: ["Matt Groening", "Seth MacFarlane", "Stephen Hillenburg", "Butch Hartman"], correctIndex: 2),

        // Tech (35+)
        TriviaQuestion(category: "Tech", question: "What does CPU stand for?", answers: ["Central Process Unit", "Central Processing Unit", "Computer Personal Unit", "Central Program Utility"], correctIndex: 1),
        TriviaQuestion(category: "Tech", question: "Who co-founded Apple Computer?", answers: ["Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Jeff Bezos"], correctIndex: 1),
        TriviaQuestion(category: "Tech", question: "What does HTML stand for?", answers: ["Hyper Tool Markup Language", "HyperText Markup Language", "Home Text Markup Language", "HyperText Making Language"], correctIndex: 1),
        TriviaQuestion(category: "Tech", question: "What programming language is known as the language of the web?", answers: ["Python", "Java", "JavaScript", "C++"], correctIndex: 2),
        TriviaQuestion(category: "Tech", question: "What year was Google founded?", answers: ["1996", "1998", "2000", "2002"], correctIndex: 1),
        TriviaQuestion(category: "Tech", question: "What does RAM stand for?", answers: ["Read Access Memory", "Random Access Memory", "Run Application Memory", "Rapid Access Module"], correctIndex: 1),
        TriviaQuestion(category: "Tech", question: "Who is the CEO of Tesla?", answers: ["Jeff Bezos", "Tim Cook", "Elon Musk", "Sundar Pichai"], correctIndex: 2),
        TriviaQuestion(category: "Tech", question: "What does USB stand for?", answers: ["Universal System Bus", "Universal Serial Bus", "Unified Serial Bus", "Ultra System Bus"], correctIndex: 1),
        TriviaQuestion(category: "Tech", question: "What is the most popular operating system for smartphones?", answers: ["iOS", "Windows", "Android", "Linux"], correctIndex: 2),
        TriviaQuestion(category: "Tech", question: "What does AI stand for?", answers: ["Artificial Intelligence", "Automated Interface", "Applied Integration", "Analog Input"], correctIndex: 0),
        TriviaQuestion(category: "Tech", question: "What company makes the iPhone?", answers: ["Samsung", "Google", "Apple", "Microsoft"], correctIndex: 2),
        TriviaQuestion(category: "Tech", question: "What is the main language used for iOS development?", answers: ["Java", "Kotlin", "Swift", "Dart"], correctIndex: 2),
        TriviaQuestion(category: "Tech", question: "What does Wi-Fi stand for?", answers: ["Wireless Fidelity", "Wireless Finder", "Wide Frequency", "It\' a brand name"], correctIndex: 0),
        TriviaQuestion(category: "Tech", question: "What is the smallest unit of data in computing?", answers: ["Byte", "Bit", "Nibble", "Word"], correctIndex: 1),
        TriviaQuestion(category: "Tech", question: "What company created Windows?", answers: ["Apple", "IBM", "Google", "Microsoft"], correctIndex: 3),
        TriviaQuestion(category: "Tech", question: "What does IoT stand for?", answers: ["Internet of Things", "Integration of Tech", "Input of Text", "Internet of Tech"], correctIndex: 0),
        TriviaQuestion(category: "Tech", question: "What is the most used search engine?", answers: ["Bing", "Yahoo", "Google", "DuckDuckGo"], correctIndex: 2),
        TriviaQuestion(category: "Tech", question: "How many bits are in a byte?", answers: ["4", "6", "8", "16"], correctIndex: 2),
        TriviaQuestion(category: "Tech", question: "What does PDF stand for?", answers: ["Portable Document Format", "Print Document File", "Personal Data Format", "Public Document Format"], correctIndex: 0),
        TriviaQuestion(category: "Tech", question: "Who invented the World Wide Web?", answers: ["Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Vint Cerf"], correctIndex: 1),
        TriviaQuestion(category: "Tech", question: "What is cloud computing?", answers: ["Weather data", "Remote servers", "Physical storage", "Local network"], correctIndex: 1),
        TriviaQuestion(category: "Tech", question: "What does VPN stand for?", answers: ["Virtual Private Network", "Very Private Network", "Visual Processing Node", "Virtual Public Network"], correctIndex: 0),
        TriviaQuestion(category: "Tech", question: "What year was the first email sent?", answers: ["1965", "1971", "1978", "1983"], correctIndex: 1),
        TriviaQuestion(category: "Tech", question: "What is Linux?", answers: ["A browser", "An operating system", "A database", "A language"], correctIndex: 1),
        TriviaQuestion(category: "Tech", question: "What does GPU stand for?", answers: ["General Processing Unit", "Graphics Processing Unit", "Global Program Utility", "Graphics Program Unit"], correctIndex: 1),
        TriviaQuestion(category: "Tech", question: "What company owns Instagram?", answers: ["Google", "Twitter", "Meta", "Snapchat"], correctIndex: 2),
        TriviaQuestion(category: "Tech", question: "What does SSD stand for?", answers: ["Solid State Drive", "System Storage Device", "Secure Serial Disk", "Super Speed Drive"], correctIndex: 0),
        TriviaQuestion(category: "Tech", question: "What programming language was created by Guido van Rossum?", answers: ["Java", "Ruby", "Python", "Go"], correctIndex: 2),
        TriviaQuestion(category: "Tech", question: "What is Bluetooth named after?", answers: ["A scientist", "A king", "A mountain", "A river"], correctIndex: 1),
        TriviaQuestion(category: "Tech", question: "What was the first programmable computer?", answers: ["ENIAC", "UNIVAC", "Z3", "Colossus"], correctIndex: 2),
        TriviaQuestion(category: "Tech", question: "What does CSS stand for?", answers: ["Cascading Style Sheets", "Computer Style System", "Creative Style Sheets", "Coded Style Syntax"], correctIndex: 0),
        TriviaQuestion(category: "Tech", question: "Which company makes the Pixel phone?", answers: ["Apple", "Samsung", "Google", "OnePlus"], correctIndex: 2),
        TriviaQuestion(category: "Tech", question: "What is 1024 bytes?", answers: ["1 Megabyte", "1 Kilobyte", "1 Gigabyte", "1 Terabyte"], correctIndex: 1),
        TriviaQuestion(category: "Tech", question: "What does API stand for?", answers: ["Application Programming Interface", "Automated Program Integration", "Application Process Input", "Advanced Protocol Interface"], correctIndex: 0),
        TriviaQuestion(category: "Tech", question: "Who is the founder of Amazon?", answers: ["Elon Musk", "Jeff Bezos", "Larry Page", "Jack Ma"], correctIndex: 1),

        // Geography (35+)
        TriviaQuestion(category: "Geography", question: "What is the largest continent?", answers: ["Africa", "Europe", "North America", "Asia"], correctIndex: 3),
        TriviaQuestion(category: "Geography", question: "What is the longest river in the world?", answers: ["Amazon", "Nile", "Mississippi", "Yangtze"], correctIndex: 1),
        TriviaQuestion(category: "Geography", question: "What is the capital of France?", answers: ["London", "Berlin", "Madrid", "Paris"], correctIndex: 3),
        TriviaQuestion(category: "Geography", question: "Which ocean is the largest?", answers: ["Atlantic", "Indian", "Arctic", "Pacific"], correctIndex: 3),
        TriviaQuestion(category: "Geography", question: "What country has the most people?", answers: ["India", "USA", "China", "Indonesia"], correctIndex: 0),
        TriviaQuestion(category: "Geography", question: "What is the smallest country in the world?", answers: ["Monaco", "San Marino", "Vatican City", "Liechtenstein"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "Mount Everest is located in which mountain range?", answers: ["Andes", "Alps", "Rocky", "Himalayas"], correctIndex: 3),
        TriviaQuestion(category: "Geography", question: "What is the capital of Japan?", answers: ["Osaka", "Kyoto", "Tokyo", "Hiroshima"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "The Sahara Desert is in which continent?", answers: ["Asia", "Australia", "Africa", "South America"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "What is the capital of Australia?", answers: ["Sydney", "Melbourne", "Canberra", "Perth"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "Which country has the most islands?", answers: ["Philippines", "Indonesia", "Sweden", "Japan"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "What is the deepest ocean trench?", answers: ["Tonga Trench", "Mariana Trench", "Java Trench", "Puerto Rico Trench"], correctIndex: 1),
        TriviaQuestion(category: "Geography", question: "What river flows through London?", answers: ["Seine", "Danube", "Thames", "Rhine"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "What is the capital of Brazil?", answers: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "Which is the largest desert in the world?", answers: ["Sahara", "Gobi", "Antarctic", "Arabian"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "What country is known as the Land of the Rising Sun?", answers: ["China", "Korea", "Japan", "Thailand"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "What is the capital of Canada?", answers: ["Toronto", "Vancouver", "Montreal", "Ottawa"], correctIndex: 3),
        TriviaQuestion(category: "Geography", question: "The Amazon Rainforest is mostly in which country?", answers: ["Colombia", "Peru", "Brazil", "Venezuela"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "What is the highest waterfall in the world?", answers: ["Niagara Falls", "Victoria Falls", "Iguazu Falls", "Angel Falls"], correctIndex: 3),
        TriviaQuestion(category: "Geography", question: "What country is shaped like a boot?", answers: ["Greece", "Spain", "Italy", "Portugal"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "What is the largest lake in Africa?", answers: ["Lake Chad", "Lake Tanganyika", "Lake Victoria", "Lake Malawi"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "What is the capital of Egypt?", answers: ["Alexandria", "Cairo", "Luxor", "Giza"], correctIndex: 1),
        TriviaQuestion(category: "Geography", question: "Which country has the longest coastline?", answers: ["Australia", "Russia", "Indonesia", "Canada"], correctIndex: 3),
        TriviaQuestion(category: "Geography", question: "What is the largest island in the world?", answers: ["Madagascar", "Borneo", "Greenland", "New Guinea"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "What is the capital of Germany?", answers: ["Munich", "Hamburg", "Berlin", "Frankfurt"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "Which two continents does Russia span?", answers: ["Europe and Africa", "Asia and Africa", "Europe and Asia", "Asia and North America"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "What is the tallest mountain in North America?", answers: ["Mount Whitney", "Denali", "Mount Rainier", "Mount Logan"], correctIndex: 1),
        TriviaQuestion(category: "Geography", question: "The Great Barrier Reef is located off which country?", answers: ["New Zealand", "Indonesia", "Australia", "Philippines"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "What sea lies between Europe and Africa?", answers: ["Red Sea", "Caribbean Sea", "Black Sea", "Mediterranean Sea"], correctIndex: 3),
        TriviaQuestion(category: "Geography", question: "What is the capital of India?", answers: ["Mumbai", "Kolkata", "New Delhi", "Bangalore"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "What is the driest continent?", answers: ["Africa", "Australia", "Antarctica", "Asia"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "What country is home to the kangaroo?", answers: ["New Zealand", "South Africa", "Australia", "Papua New Guinea"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "The Danube River flows through how many countries?", answers: ["5", "8", "10", "12"], correctIndex: 2),
        TriviaQuestion(category: "Geography", question: "What is the smallest US state?", answers: ["Delaware", "Connecticut", "Rhode Island", "New Hampshire"], correctIndex: 2),
    ]

    static func questions(forCategory category: String, count: Int = 10) -> [TriviaQuestion] {
        let filtered = category == "All" ? questions : questions.filter { $0.category == category }
        return Array(filtered.shuffled().prefix(count))
    }

    static var categories: [String] {
        Array(Set(questions.map { $0.category })).sorted()
    }
}
