import Foundation

struct TriviaQuestion: Codable {
    let question: String
    let answers: [String]
    let correctIndex: Int
}

struct TriviaCrushQuestionBank {
    static let questions = [
        TriviaQuestion(question: "What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[1] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[1] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[1] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[1] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[1] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[1] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[1] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[1] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[1] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[1] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[2] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[2] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[2] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[2] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[2] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[2] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[2] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[2] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[2] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[2] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[3] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[3] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[3] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[3] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[3] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[3] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[3] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[3] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[3] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[3] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[4] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[4] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[4] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[4] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[4] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[4] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[4] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[4] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[4] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[4] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[5] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[5] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[5] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[5] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[5] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[5] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[5] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[5] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[5] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[5] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[6] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[6] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[6] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[6] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[6] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[6] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[6] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[6] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[6] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[6] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[7] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[7] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[7] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[7] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[7] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[7] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[7] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[7] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[7] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[7] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[8] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[8] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[8] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[8] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[8] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[8] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[8] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[8] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[8] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[8] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[9] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[9] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[9] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[9] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[9] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[9] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[9] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[9] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[9] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[9] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[10] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[10] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[10] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[10] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[10] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[10] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[10] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[10] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[10] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[10] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[11] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[11] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[11] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[11] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[11] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[11] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[11] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[11] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[11] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[11] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[12] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[12] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[12] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[12] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[12] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[12] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[12] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[12] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[12] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[12] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[13] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[13] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[13] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[13] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[13] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[13] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[13] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[13] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[13] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[13] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[14] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[14] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[14] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[14] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[14] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[14] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[14] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[14] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[14] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[14] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[15] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[15] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[15] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[15] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[15] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[15] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[15] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[15] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[15] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[15] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[16] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[16] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[16] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[16] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[16] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[16] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[16] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[16] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[16] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[16] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[17] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[17] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[17] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[17] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[17] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[17] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[17] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[17] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[17] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[17] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[18] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[18] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[18] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[18] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[18] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[18] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[18] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[18] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[18] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[18] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[19] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[19] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[19] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[19] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[19] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[19] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[19] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[19] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[19] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[19] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
        TriviaQuestion(question: "[20] What is the largest planet in our solar system?", answers: ["Earth", "Mars", "Jupiter", "Saturn"], correctIndex: 2),
        TriviaQuestion(question: "[20] What is the capital of France?", answers: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2),
        TriviaQuestion(question: "[20] Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1),
        TriviaQuestion(question: "[20] What is the chemical symbol for water?", answers: ["O2", "H2O", "CO2", "NaCl"], correctIndex: 1),
        TriviaQuestion(question: "[20] Which element has the atomic number 1?", answers: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2),
        TriviaQuestion(question: "[20] How many continents are there?", answers: ["5", "6", "7", "8"], correctIndex: 2),
        TriviaQuestion(question: "[20] What is the smallest prime number?", answers: ["0", "1", "2", "3"], correctIndex: 2),
        TriviaQuestion(question: "[20] Who wrote 'Romeo and Juliet'?", answers: ["Mark Twain", "Charles Dickens", "William Shakespeare", "Jane Austen"], correctIndex: 2),
        TriviaQuestion(question: "[20] What is the fastest land animal?", answers: ["Lion", "Cheetah", "Horse", "Gazelle"], correctIndex: 1),
        TriviaQuestion(question: "[20] Which country is home to the Great Barrier Reef?", answers: ["USA", "Brazil", "Australia", "Thailand"], correctIndex: 2),
    ]
}
